POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZDkxZDIxMjcyMTI2OWEwYTY3NjMwZCIsImlhdCI6MTY3NTE3NjM0NH0.uSHlt8tr2DcUf8ShQ-Y2TDqcuq_gVuQR8oHQp2q4Lsk

{
  	"content": "This is my second note",
	"important": true,
	"userId": "63d91d212721269a0a67630d"
}

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/63d91e552d832c0ad51ca095

###
DELETE http://localhost:3001/api/notes/63ab23b73fd76405e3903d20

###
PUT http://localhost:3001/api/notes/63a57aed444feb8ad3d496bc
Content-Type: application/json

{
  	"content": "This",
	"important": false
}

### users

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
GET http://localhost:3001/api/users